### ISSUE TITLE
Auxgen

### ISSUE THREAD

**Issue by ghost** [AzAgarampur/byeintegrity-uac#4]
what is it ?

**Comment by AzAgarampur** [comment]
From the README:

> The updated version of ByeIntegrity comes with a tool called AUXGen, which takes in the name of an assembly from the GAC and then generates its corresponding AUX file. The AUX file is generated so that it matches the CLR's checks and the CLR will load the "native image" which is described by the AUX file. Note: AUXGen does not handle dependencies when generating the AUX file. It only does as much as it needs to so that the CLR will load the image. I will post details of the AUX file format later.

**Comment by ghost** [comment]
do we have to compile the auxgen with the byeintegrity
