### ISSUE TITLE
can u recommend some Ide to compile it? or should we just use vs

### ISSUE THREAD

**Issue by ghost** [AzAgarampur/byeintegrity-uac#6]
Im not the smartest but i have visual studio open and i was wondering we dont compile the payload too right?

**Comment by ghost** [comment]
stupid question

**Comment by ghost** [comment]
yo when i compile it, it asks for file operation and that needs admin. but the thing is i wanted to use a uac bypass thats fud and doesnt need admin so because im i forgot the admin password and dont wanna do something complicated

**Comment by AzAgarampur** [comment]
You must be running it under a user account that is part of the administrators group. It will not work if you run it from a standard user account.
